# Generated by Django 5.0.6 on 2024-05-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_competence_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='twitter',
            new_name='youtube',
        ),
    ]
